export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_LOADING_FALSE = 'PROFILE_LOADING_FALSE';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';


export const POST_LOADING = 'POST_LOADING';
export const GET_POSTS = 'GET_POSTS';
export const GET_POST = 'GET_POST';
export const ADD_POST = 'ADD_POST';
export const DELETE_POST = 'DELETE_POST';

export const GET_DIET = 'GET_DIET';
export const GET_DIET_BY_ID = 'GET_DIET_BY_ID';
export const GET_DIET_BY_ID_WITHOUT_LOADING = 'GET_DIET_BY_ID_WITHOUT_LOADING';
export const GET_DIETS = 'GET_DIETS';
export const DIET_LOADING = 'DIET_LOADING';
export const ADD_DIET = 'ADD_DIET';
export const UPDATE_DIET = 'UPDATE_DIET';
export const UPDATE_DIET_SINGLE_PAGE = 'UPDATE_DIET_SINGLE_PAGE';
export const UPDATE_DIET_PROFILE_PAGE = 'UPDATE_DIET_PROFILE_PAGE';
export const DELETE_DIET = 'DELETE_DIET';
export const DELETE_DIET_PROFILE_PAGE = 'DELETE_DIET_PROFILE_PAGE';
export const ADD_COMMENT_DIET = 'ADD_COMMENT_DIET';
export const DELETE_COMMENT_DIET = 'DELETE_COMMENT_DIET';
export const LIKE_DIET = 'LIKE_DIET';


export const GET_RECIPE_BY_ID = 'GET_RECIPE_BY_ID';
export const GET_RECIPE_BY_ID_WITHOUT_LOADING = 'GET_RECIPE_BY_ID_WITHOUT_LOADING';
export const GET_RECIPES = 'GET_RECIPES';
export const RECIPE_LOADING = 'RECIPE_LOADING';
export const DELETE_RECIPE_PROFILE_PAGE = 'DELETE_RECIPE_PROFILE_PAGE';
export const ADD_RECIPE = 'ADD_RECIPE';
export const LIKE_RECIPE = 'LIKE_RECIPE';


export const GET_MAPS = 'GET_MAPS';
export const MAP_LOADING = 'MAP_LOADING';


export const SEND_EMAIL = 'SEND_EMAIL';
export const EMAIL_LOADING = 'EMAIL_LOADING';

